### ISSUE TITLE
[Feature] 

### ISSUE THREAD

**Issue by lqs01** [ayasa520/waydroid-helper#13]
### Is your feature request related to a problem? Please describe.

I have some own configurationlines in `cat /var/lib/waydroid/waydroid_base.prop`. If I use Restart(update config), there will be overwritten.

### Describe the solution you'd like.

Ability in the app to add some own lines, so there will be added if I update the config with the app.

### Describe alternatives you've considered.

Don't overwrite own configlines.

**Comment by ayasa520** [comment]
This is expected because `/var/lib/waydroid/waydroid_base.prop` is automatically regenerated at every waydroid  upgrade, which causes manual changes to be overwritten.

Instead of modifying `/var/lib/waydroid/waydroid_base.prop` directly, you should add your custom props to `/var/lib/waydroid/waydroid.cfg` under the `[properties]` section. After making the changes, run the command:

```
waydroid upgrade --offline
```

This will regenerate the waydroid_base.prop file, including your custom props.

https://github.com/casualsnek/waydroid_script/issues/78

**Comment by lqs01** [comment]
Hey. Thank you for your detailed answer. I didn't know this behavior.
